<?php
/**
 * Created by PhpStorm.
 * User: ishwar
 * Date: 7/3/18
 * Time: 2:47 PM
 */

namespace Javra\Bannerslider\Controller\Adminhtml;


use Javra\Bannerslider\Controller\Adminhtml\AbstractAction;

abstract class Slider extends AbstractAction
{
    const PARM_CRUD_ID = 'slider_id';

    /**
     * check admin has permission to access related page.
     * @return bool
     */
    protected function _isAllowed()
    {
        return $this->_authorization->isAllowed('Javra_Bannerslider::bannerslider_sliders'); // TODO: Change the autogenerated stub
    }


}