<h1>Name</h1>

<?php $postCollection = $block->getCollection();
echo $postCollection;
?>
<!--<form action="--><?php //echo $block->getCount() ?><!--" method="post">-->
<!--    <input name="firstname" type="text">-->
<!--    <input name="lastname" type="text">-->
<!--    <input name="phone" type="text">-->
<!--    <input name="bookingTime" type="date">-->
<!--    <input type="submit" value="Send booking informations">-->
<!--</form>-->